version: '3'
services:
  mlflow:
    container_name: mlflow
    build: .
    image: mlflow-tracking:1.0
    environment:
      TZ: Asia/Tokyo
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      BACKEND_STORE_URI: ${BACKEND_STORE_URI}
      DEFAULT_ARTIFACT_ROOT: ${DEFAULT_ARTIFACT_ROOT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio

  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Asia/Tokyo"

  pgadmin:
    image: dpage/pgadmin4
    container_name: db-cl
    ports:
      - 5050:5050
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000 # API用
      - 9001:9001 # コンソール用
    volumes:
      - mindata:/export
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /export --address :9000 --console-address :9001

volumes:
  pgdata:
  pgadmin4_data:
  mindata:
