version: '3'
services:
  # minioコンテナ起動時にデフォルトのバケットを自動作成する
  # https://hub.docker.com/r/minio/mc/
  defaultbucket:
    image: minio/mc
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://host.docker.internal:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/mlflow;
      /usr/bin/mc anonymous download myminio/mlflow;
      exit 0;
      "
    depends_on:
      - minio